NutInf/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth.decorators import login_required

#from NutInf import views
from .views import listarNutInfo, crearNut_Info, editarNutInfo, eliminarNutInfo, Inicio, crearProducto, listarProducto, listarNutProduct




urlpatterns = [
    
    path('indiceNut/', login_required(Inicio.as_view()), name="ValorNut"),
    path('crear_valor/', login_required(crearNut_Info.as_view()), name="crear_valor"),
    path('lista_valores/', login_required(listarNutInfo.as_view()), name="lista_valores"),
    path('editar_valor/<int:pk>', login_required(editarNutInfo.as_view()), name="editar_valor"),
    path('eliminar_valor/<int:pk>', login_required(eliminarNutInfo.as_view()), name="eliminar_valor"),
    path('crear_producto/', login_required(crearProducto.as_view()), name="crear_producto"),
    path('lista_productos/', login_required(listarProducto.as_view()), name="lista_productos"),
    path('lista_totales/', login_required(listarNutProduct.as_view()), name="lista_totales"),

]

Restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('users.urls', 'users'))),
    path('', include(('NutInf.urls', 'nutinf'))),
    path('accounts/', include('django.contrib.auth.urls')),
       
]

users/urls.py
from django.conf.urls import url
from django.urls import path
from users import views



urlpatterns = [
    path('', views.login, name="Login"),
    path('register/', views.register, name="Registro"),
    path('welcome/', views.welcome),

]

NutInf/models.py
from django.db import models

class Nutinf(models.Model):
    name=models.CharField(max_length=20)
    unit=models.CharField(max_length=5)

    class Meta:
        verbose_name='nutinf'
        verbose_name_plural='nutinfs'

    def __str__(self):
        return "%s (%s)" %(self.name, self.unit)
  

class Products(models.Model):
    name_product=models.CharField(max_length=20)
    description=models.TextField()
    nutval=models.ManyToManyField(Nutinf)
    active=models.BooleanField(default=True)

    class Meta:
        verbose_name='product'
        verbose_name_plural='products'

    def __str__(self):
        return self.name_product

class NutProduct(models.Model):
    nut_id=models.ForeignKey(Nutinf, on_delete=models.CASCADE)
    product_id=models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity=models.FloatField(default=1)

    class Meta:
        verbose_name='nutproduct'
        verbose_name_plural='nutproducts'

users/models.py
from django.db import models

# Create your models here.

NutInf/forms.py
from django import forms
from .models import Nutinf, Products

class NutinfForm(forms.ModelForm):
    class Meta:
        model=Nutinf
        fields=['name','unit']
        
        widgets={
            'name': forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Energy value',
                    }
                ),
            'unit': forms.TextInput(
                attrs={
                    'class':'form-control',
                    'placeholder':'Unit of measure',
                    }
                )

            }

class ProductsForm(forms.ModelForm):
    class Meta:
        model=Products
        fields=['name_product', 'description', 'nutval', 'active']

NutInf/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, UpdateView, CreateView, DeleteView
from .forms import NutinfForm, ProductsForm
from NutInf.models import Nutinf, Products, NutProduct


class Inicio(TemplateView):
    template_name= 'NutInf/indiceNut.html'

class crearNut_Info(CreateView):
    model= Nutinf
    template_name= 'NutInf/crear_valor.html'
    form_class= NutinfForm
    success_url= '/lista_valores'

class listarNutInfo(ListView):
    model= Nutinf
    template_name='NutInf/lista_valores.html'
    context_object_name='infonuts'
    queryset= Nutinf.objects.all()

class editarNutInfo(UpdateView):
    model= Nutinf
    template_name= 'NutInf/crear_valor.html'
    form_class= NutinfForm
    success_url= '/lista_valores'

class eliminarNutInfo(DeleteView):
    model= Nutinf
    template_name= 'NutInf/eliminar_valor.html'
    form_class= NutinfForm
    success_url= '/lista_valores'


class crearProducto(CreateView):
    model= Products
    template_name= 'NutInf/crear_producto.html'
    form_class= ProductsForm
    success_url= '/lista_productos'

class listarProducto(ListView):
    model= Products
    template_name='NutInf/lista_productos.html'
    context_object_name='products'
    queryset= Products.objects.all()

class listarNutProduct(ListView):
    model= NutProduct
    template_name='NutInf/lista_totales.html'
    context_object_name='nutproducts'
    queryset= NutProduct.objects.all()
    

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout as do_logout
from django.contrib.auth import login as do_login
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.http import HttpResponse


def home(request):
    
    return render(request,"users/home.html")

'''def index(request):
    
    # Creamos el formulario de autenticación vacío
    form = AuthenticationForm()
    if request.method == "POST":
        # Añadimos los datos recibidos al formulario
        form = AuthenticationForm(data=request.POST)
        # Si el formulario es válido...
        if form.is_valid():
            # Recuperamos las credenciales validadas
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # Verificamos las credenciales del usuario
            user = authenticate(username=username, password=password)

            # Si existe un usuario con ese nombre y contraseña
            if user is not None:
                # Hacemos el login manualmente
                do_login(request, user)
                # Y le redireccionamos a la portada
            return redirect('/welcome')

    # Si llegamos al final renderizamos el formulario
    return render(request, "users/index.html", {'form': form})'''


def welcome(request):
    if request.user.is_authenticated:
        return render(request, "users/welcome.html")
    return redirect('login')
    

def register(request):
     # Creamos el formulario de autenticación vacío
    form = UserCreationForm()
    if request.method == "POST":
        # Añadimos los datos recibidos al formulario
        form = UserCreationForm(data=request.POST)
        # Si el formulario es válido...
        if form.is_valid():

            # Creamos la nueva cuenta de usuario
            user = form.save()

            # Si el usuario se crea correctamente 
            if user is not None:
                # Hacemos el login manualmente
                do_login(request, user)
                # Y le redireccionamos a la portada
                return redirect('/')
            
    form.fields['username'].help_text = None
    form.fields['password1'].help_text = None
    form.fields['password2'].help_text = None
    

    # Si llegamos al final renderizamos el formulario
    return render(request, "users/register.html", {'form': form})

def login(request):
    # Creamos el formulario de autenticación vacío
    form = AuthenticationForm()
    if request.method == "POST":
        # Añadimos los datos recibidos al formulario
        form = AuthenticationForm(data=request.POST)
        # Si el formulario es válido...
        if form.is_valid():
            # Recuperamos las credenciales validadas
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # Verificamos las credenciales del usuario
            user = authenticate(username=username, password=password)

            # Si existe un usuario con ese nombre y contraseña
            if user is not None:
                # Hacemos el login manualmente
                do_login(request, user)
                # Y le redireccionamos a la portada
            return redirect('/indiceNut')

    # Si llegamos al final renderizamos el formulario
    return render(request, "users/login.html", {'form': form})

def logout(request):
    do_logout(request)
    # Redireccionamos a la portada
    return redirect('/')

templates/Nutinf/crear_producto.html
{% extends "users/base.html" %}

{% load static %}

{% block barra %}{% endblock %}

{% block content %}
<body class="text-center"></body>

<h2 style="color: seashell;">Create Product</h2>

<form class="form-nut" method="POST">
    {{ form }}
    {% csrf_token %}
    
    <button type="submit" style="cursor: pointer;" class="btn btn-secundary">Create/Edit</button>
    <button type="submit" style="cursor: pointer; " class="btn btn-primary"><a href= "/lista_productos" style="color: seashell;">Cancel</a></button>
</form>



</body>

{% endblock %}

templates/Nutinf/crear_valor.html
{% extends "users/base.html" %}

{% load static %}

{% block barra %}{% endblock %}

{% block content %}
<body class="text-center"></body>

<h2 style="color: seashell;">Create Nutricional Information</h2>

<form class="form-nut" method="POST">
    {{ form }}
    {% csrf_token %}
    
    <button type="submit" style="cursor: pointer;" class="btn btn-secundary">Create/Edit</button>
    <button type="submit" style="cursor: pointer; " class="btn btn-primary"><a href= "/lista_valores" style="color: seashell;">Cancel</a></button>
</form>



</body>

{% endblock %}

templates/Nutinf/eliminar_valor.html
{% extends "users/base.html" %}

{% load static %}

{% block barra %}{% endblock %}

{% block content %}
<body class="text-center"></body>

<h2 style="color: seashell;">Create Nutricional Information</h2>

<form method="POST">
    {% csrf_token %}
    <h2 style="color: seashell;">¿Are you sure you want to delete {{ object }}?</h2>
    <input type="submit" value="Remove">
    <input type="button" onclick="location.href='/lista_valores'" value="Cancel">
</form>



</body>

{% endblock %}

templates/Nutinf/indiceNut.html
{% extends "users/base.html" %}

{% load static %}

{% block barra %}
<p style="color: seashell;">Welcome <b>{{request.user.username}}</b></p>

{% endblock %}

{% block content %}
<body class="text-center"></body>

<h2><a style="color: seashell;" href="/lista_valores"> Nutricional Information</a></h2>
<h2><a style="color: seashell;" href="/lista_productos"> Products</a></h2>




</body>

{% endblock %}

templates/Nutinf/lista_productos.html
{% extends "users/base.html" %}

{% load static %}

{% block barra %}
<body class="text-center"></body>

<h2 style="color: seashell;">List Products</h2>

</body>

{% endblock %}

{% block content %}

{% if products %}
        <table class="form-product" border="1">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Active</th>

                    
                    

                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                
                    <tr>
                        <td>{{ product.name_product }} </td>
                        <td width="75%">{{ product.description }}</td>
                        <td>{{ product.active }} </td>
                        
                        {% if perms.NutInf.change_product %}
                        <td><a href="/editar_valor/{{ infonut.id }}" style="color: blanchedalmond;">Edit</a></td>
                        {% endif %}
                        {% if perms.NutInf.delete_product %}
                        <td><a href="/eliminar_valor/{{ infonut.id }}" style="color: blanchedalmond;">Remove</a></td>
                        {% endif %}
                    </tr>
                    
                {% endfor %}
                
            </tbody>
        </table>

    {% else %}
         <h1>No existe valores</h1>
    {% endif %}
      <br/>
    <button type="button">
        {% if perms.NutInf.add_product %}
        <input type="button" onclick="location.href='/crear_producto'" value="Create product" style="cursor: pointer;">
        {% endif %}
    </button>



{% endblock %}

templates/Nutinf/lista_totales.html
{% extends "users/base.html" %}

{% load static %}

{% block barra %}
<body class="text-center"></body>

<h2 style="color: seashell;">List Products</h2>

</body>

{% endblock %}

{% block content %}

{% if nutproducts %}
        <table class="form-product" border="1">
            <thead>
                <tr>
                    <th>Name</th>
                 
                </tr>
            </thead>
            <tbody>
              

                {% for nutproduct in nutproducts %}
                
                    <tr>
                        
                        <td>{{ nutproduct.product_id }} </td>
                        <td>{{ nutproduct.nut_id }} </td>
                        <td>{{ nutproduct.quantity }} </td>
                        
                        
                    </tr>
                    
                {% endfor %}
                    
                
            </tbody>
        </table>

    {% else %}
         <h1>No existe valores</h1>
    {% endif %}
     

    <br/>
   



{% endblock %}

templates/Nutinf/lista_valores.html
{% extends "users/base.html" %}

{% load static %}

{% block barra %}
<body class="text-center"></body>

<h2 style="color: seashell;">List Nutricional Information</h2>

</body>

{% endblock %}

{% block content %}

{% if infonuts %}
        <table class="form-nut">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Unit</th>
                    

                </tr>
            </thead>
            <tbody>
                {% for infonut in infonuts %}
                
                    <tr>
                        <td>{{ infonut.name }} </td>
                        <td>{{ infonut.unit }} </td>
                        {% if perms.NutInf.change_nutinf %}
                        <td><a href="/editar_valor/{{ infonut.id }}" style="color: blanchedalmond;">Edit</a></td>
                        {% endif %}
                        {% if perms.NutInf.delete_nutinf %}
                        <td><a href="/eliminar_valor/{{ infonut.id }}" style="color: blanchedalmond;">Remove</a></td>
                        {% endif %}
                    </tr>
                    
                {% endfor %}
            </tbody>
        </table>

    {% else %}
         <h1>No existe valores</h1>
    {% endif %}
    <br/>
    <button type="button">
        {% if perms.NutInf.add_nutinf %}
        <input type="button" onclick="location.href='/crear_valor'" value="Create nutritional informations" style="cursor: pointer;">
        {% endif %}
    </button>



{% endblock %}

templates/users/login.html
{% extends "users/base.html" %}

{% load static %}

{% block barra %}{% endblock %}

{% block content %}
<link href="{% static 'users/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

<body class="text-center">

    
    
    <form class="form-signin" method="POST" style="color: seashell;">
        {{ form }}
        {% csrf_token %}
        <button type="submit" class="btn btn-default btn-lg">Login</button>
    </form>
    
    
    <a href="/register" style="color: seashell;">Register user</a>
 </body> 


{% endblock %}

templates/users/register.html
{% extends "users/base.html" %}

{% load static %}

{% block barra %}{% endblock %}

{% block content %}
<body class="text-center"></body>



<form class="form-signin" method="POST" style="color: seashell;">
    {{ form.as_p }}
    {% csrf_token %}
    <button type="submit" class="btn btn-default btn-lg">Register</button>
</form>

<hr />

<a href="/" style="color: seashell;">Login</a>
</body>

{% endblock %}

templates/users/welcome.html
<h2>Área para miembros</h2>

<p>
    Bienvenido <b>{{request.user.username}}</b>, 
    esta página es exclusiva para usuarios registrados.
</p>

<hr />
<a href="/">Cerrar sesión</a>

users/templates/users/NutInf.html
{% extends "users/base.html" %}

{% load static %}

{% block content %}

   <!-- Heading -->
   <section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'users/img/principal.jpg' %}" alt="">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4" >
            <span class="section-heading-upper">Puntualidad</span>
            <span class="section-heading-lower">El mejor stock</span>
          </h2>
          <p class="mb-3">En la puertra de tu casa en menos de 48 h con el envío normal. En menos de 24 h con el envío express.
          </p>
         
        </div>
      </div>
    </div>
  </section>


  
    <!-- Message -->
    <section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-4">
                <span class="section-heading-upper">Compromiso total</span>
                <span class="section-heading-lower">Garantizado</span>
              </h2>
              <p class="mb-0">Con más de 75 años de experiencia a nuestras espaldas, desde Gestión de Pedidos tenemos los conocimientos y herramientas necesarios para llevar cualquier objeto a la puerta de su casa con puntualidad y profesionalidad.</p>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock %}

users/templates/users/base.html
<html>

<head>

    {% load static %}


    <!-- Bootstrap -->
    <link href="{% static 'users/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

     <!-- Fonts -->
    
     <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet"> 
     <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
     

    <!-- Styles -->
    <link href="{% static 'users/css/gestion.css' %}" rel="stylesheet">
</head>

<body>
  {% if user.is_authenticated %}
      
  <li>
    <a href="{% url 'logout' %}" >cerrar sesión</a> 
  </li>
  {% else %}
  <li>
    <a href="{% url 'login' %}">iniciar sesión</a> 
  </li>
  {% endif %}
    <h1 class="site-heading text-center text-white d-none d-lg-block">
      
        <span class="site-heading-lower">Restaurant</span>
        
      </h1>
      
      
      
 {% block barra %}
 <!-- Navbar -->
 <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
      <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="{% url 'Home' %}">Gestión de Pedidos</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item active px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Home' %}">Inicio</a>
          </li>
          <li class="nav-item px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Login' %}">Login</a>
          </li>
          <li class="nav-item px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'Registro' %}">Registro</a>
          </li>
         
         
        </ul>
      </div>
    </div>
  </nav>
 {% endblock %}

 {% block content %}

 {% endblock %}


    <!-- Footer -->
    <footer class="footer text-faded text-center py-5">
      <div class="container">
        <p class="m-0">
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	        <a href="#" class="link">
	          <span class="fa-stack fa-lg">
	            <i class="fa fa-circle fa-stack-2x"></i>
	            <i class="fa fa-instagram fa-stack-1x fa-inverse"></i>
	          </span>
	        </a>
	    </p>
        
        <p class="m-0 mbt1">&copy; Restaurant 2020</p>
      </div>
	</footer>

    <!-- Bootstrap -->
    <script src="{% static 'users/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'users/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>


</html>

users/templates/users/home.html
{% extends "users/base.html" %}

{% load static %}

{% block content %}

   <!-- Heading -->
   <section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'users/img/principal.jpg' %}" alt="">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4" >
            <span class="section-heading-upper">Puntualidad</span>
            <span class="section-heading-lower">El mejor stock</span>
          </h2>
          <p class="mb-3">En la puertra de tu casa en menos de 48 h con el envío normal. En menos de 24 h con el envío express.
          </p>
         
        </div>
      </div>
    </div>
  </section>


  
    <!-- Message -->
    <section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-4">
                <span class="section-heading-upper">Compromiso total</span>
                <span class="section-heading-lower">Garantizado</span>
              </h2>
              <p class="mb-0">Con más de 75 años de experiencia a nuestras espaldas, desde Gestión de Pedidos tenemos los conocimientos y herramientas necesarios para llevar cualquier objeto a la puerta de su casa con puntualidad y profesionalidad.</p>
            </div>
          </div>
        </div>
      </div>
    </section>

{% endblock %}

users/templates/users/index.html
<!doctype html>
<html lang="en">
  <head>

    {% load static %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">
    <title>Login Restaurante</title>

    

    <!-- Bootstrap core CSS -->
<link href="{% static 'users/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'users/css/signin.css' %}" rel="stylesheet">
  </head>
  <body class="text-center">
    <form  method="POST" class="form-signin">
  <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
  
    {{ form.as_p }}
    {% csrf_token %}
    
  
  <div class="checkbox mb-3">
    <label>
      <input type="checkbox" value="remember-me"> Remember me
    </label>
  </div>
  <button class="btn btn-lg btn-primary " type="submit">Sign in</button>
  <p class="mt-5 mb-3 text-muted">&copy; 2017-2020</p>
</form>
</body>
</html>